In [2]:
import numpy as np

In [3]:
vector = np.array([1, 2, 4, 8, 16])
print(vector)
# >>> [ 1  2  4  8 16]

matrix = np.array([[5, 10], [15, 30]])
print(matrix)
# >>> [[ 5 10], [15 30]]

[ 1  2  4  8 16]
[[ 5 10]
 [15 30]]


In [4]:
lista_1 = [100, 200, 300, 400]
lista_2 = [3, 4, 5, 6]

vector_2 = np.array(lista_1)
print(vector_2)
# >>> [100 200 300 400]

matrix_2 = np.array([lista_1, lista_2])
print(matrix_2)
# >>> [[100 200 300 400]
#  [  3   4   5   6]]

[100 200 300 400]
[[100 200 300 400]
 [  3   4   5   6]]


In [5]:
type(vector)

numpy.ndarray

In [6]:
print(vector.shape)
# >>> (5,)

print(matrix.shape)
# >>> (2, 2)

print(matrix_2.shape)
# >>> (2, 4)

(5,)
(2, 2)
(2, 4)


In [7]:
print(vector.dtype)
# >>> dtype('int64')

print(matrix.dtype)
# >>> dtype('int64')

vector_4 = np.array([1.4, 5.6, 6.8])
print(vector_4.dtype)
# >>> dtype('float64')

int32
int32
float64
